version: "3"
services:
  backend:
    container_name: backend
    image: getjv/ms2_backend
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - DOCUMENT_ROOT_CONTEXT=public
      - ALLOW_OVERRIDE_OPTION=All
      - APPLICATION_ENV_OPTION=production
    links:
      - mysql
  mysql:
    container_name: mysql
    image: getjv/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel_default_project
      - MYSQL_ROOT_PASSWORD=mysql
