version: "3"
services:
  backend:
    container_name: backend
    image: getjv/php-apache
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - DOCUMENT_ROOT_CONTEXT=public
      - ALLOW_OVERRIDE_OPTION=All
      - APPLICATION_ENV_OPTION=development
    links:
      - mysql
      - redis
  mysql:
    container_name: mysql
    image: getjv/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel_default_project
      - MYSQL_ROOT_PASSWORD=mysql
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
